//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudzetProjektu
    {
        public int budzet_id { get; set; }
        public Nullable<int> projekt_id { get; set; }
        public Nullable<decimal> calkowity_budzet { get; set; }
        public Nullable<decimal> wydana_kwota { get; set; }
        public Nullable<decimal> pozostala_kwota { get; set; }
    
        public virtual Projekty Projekty { get; set; }
    }
}
