//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogiZadan
    {
        public int log_id { get; set; }
        public Nullable<int> zadanie_id { get; set; }
        public string dzialanie { get; set; }
        public string status_przed { get; set; }
        public string status_po { get; set; }
        public Nullable<System.DateTime> data_zmiany { get; set; }
    
        public virtual Zadania Zadania { get; set; }
    }
}
