//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlikiWydarzenia
    {
        public int plik_id { get; set; }
        public Nullable<int> wydarzenie_id { get; set; }
        public string nazwa_pliku { get; set; }
        public string sciezka_pliku { get; set; }
        public Nullable<System.DateTime> data_wgrania { get; set; }
    
        public virtual Wydarzenia Wydarzenia { get; set; }
    }
}
