//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejestrCzasuPracyProjekt
    {
        public int rejestr_id { get; set; }
        public Nullable<int> projekt_id { get; set; }
        public Nullable<decimal> czas_spedzony { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Projekty Projekty { get; set; }
    }
}
