//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RyzykaProjektu
    {
        public int ryzyko_id { get; set; }
        public Nullable<int> projekt_id { get; set; }
        public string opis { get; set; }
        public string wplyw { get; set; }
        public string prawdopodobienstwo { get; set; }
        public string srodki_zapobiegawcze { get; set; }
    
        public virtual Projekty Projekty { get; set; }
    }
}
